export const themeMock = {
  space: [0, 6, 12, 24, 48, 96, 192],
  fonts: {
    body: "'IBM Plex Serif', sans-serif",
    heading: "'IBM Plex Sans', 'Helvetica'",
  },
  fontSizes: [12, 18, 24, 30, 36, 48, 72],
  fontWeights: { body: 'normal', bold: 'bold', heading: 'bold' },
  lineHeights: { body: 1.5, heading: 1.1 },
  colors: {
    green: 'rgb(92, 185, 136)',
    yellows: ['rgb(255, 199, 84)', 'rgb(255, 202, 84)'],
    blues: ['rgb(99, 173, 242)', 'rgb(215, 236, 255)', 'rgb(77, 118, 164)'],
    reds: ['rgb(255, 92, 93)', 'rgb(243, 156, 165)'],
    blacks: ['rgb(0, 0, 0)', 'rgb(54, 54, 54)'],
    whites: ['rgb(255, 255, 255)', 'rgb(247, 247, 247)', 'rgb(244, 244, 244)'],
    grays: [
      'rgb(99, 99, 99)',
      'rgb(148, 148, 148)',
      'rgb(187, 187, 187)',
      'rgb(242, 242, 242)',
    ],
  },
  styles: {
    root: {
      fontFamily: 'body',
      fontSize: 2,
      fontWeight: 'body',
      lineHeight: 'body',
    },
    img: { padding: 0, margin: 0, marginBottom: 3, maxWidth: '100%' },
    h1: {
      padding: 0,
      margin: 0,
      marginBottom: 3,
      fontSize: 5,
      fontFamily: 'heading',
      lineHeight: 'heading',
      fontWeight: 'heading',
    },
    h2: {
      padding: 0,
      margin: 0,
      marginBottom: 3,
      fontSize: 4,
      fontFamily: 'heading',
      lineHeight: 'heading',
      fontWeight: 'heading',
    },
    h3: {
      padding: 0,
      margin: 0,
      marginBottom: 3,
      fontSize: 3,
      fontFamily: 'heading',
      lineHeight: 'heading',
      fontWeight: 'heading',
    },
    h4: {
      padding: 0,
      margin: 0,
      marginBottom: 3,
      fontSize: 2,
      fontFamily: 'heading',
      lineHeight: 'heading',
      fontWeight: 'heading',
    },
    h5: {
      padding: 0,
      margin: 0,
      marginBottom: 3,
      fontSize: 1,
      fontFamily: 'heading',
      lineHeight: 'heading',
      fontWeight: 'heading',
    },
    h6: {
      padding: 0,
      margin: 0,
      marginBottom: 3,
      fontSize: 0,
      fontFamily: 'heading',
      lineHeight: 'heading',
      fontWeight: 'heading',
    },
    ul: {
      padding: 0,
      margin: 0,
      marginBottom: 3,
      listStylePosition: 'outside',
      listStyleImage: 'none',
      ml: 3,
    },
    ol: {
      padding: 0,
      margin: 0,
      marginBottom: 3,
      listStylePosition: 'outside',
      listStyleImage: 'none',
      ml: 3,
    },
    li: {
      mb: 2,
      pl: 0,
      ol: { my: 2, ml: 3 },
      ul: { my: 2, ml: 3 },
      p: { mb: 2 },
    },
    p: { padding: 0, margin: 0, marginBottom: 3 },
    table: {
      padding: 0,
      margin: 0,
      marginBottom: 3,
      borderCollapse: 'collapse',
      width: '100%',
    },
    th: {
      textAlign: 'left',
      borderBottom: '1px solid',
      px: 2,
      py: 1,
      ':first-child': { pl: 0 },
      ':last-child': { pr: 0 },
    },
    td: {
      textAlign: 'left',
      borderBottom: '1px solid',
      px: 2,
      py: 1,
      mt: '-1px',
      ':first-child': { pl: 0 },
      ':last-child': { pr: 0 },
    },
    blockquote: { padding: 0, margin: 0, marginBottom: 3, mx: 3 },
    hr: {
      padding: 0,
      margin: 0,
      marginBottom: 3,
      border: 0,
      borderBottom: '1px solid',
      mt: '-1px',
      mb: 3,
    },
    b: { fontWeight: 'bold' },
    strong: { fontWeight: 'bold' },
    code: { fontSize: '85%' },
    pre: { padding: 3, margin: 0, marginBottom: 3, fontSize: '85%' },
  },
  borderWidths: [1, 2, 3, 4],
  letterSpacings: [0.5, 1, 1.5],
  spaces: [0, 3, 6, 12, 18, 24, 30, 36, 48, 72],
  transition: {
    duration: [0.33, 0.5, 0.66, 0.99],
    timing: [
      'cubic-bezier(0.455, 0.030, 0.515, 0.955)',
      'cubic-bezier(0.075, 0.820, 0.165, 1.000)',
      'cubic-bezier(1.000, 0.000, 0.000, 1.000)',
    ],
  },
  typography: {
    options: {
      baseFontSize: 16,
      baseLineHeight: 1.5,
      headerLineHeight: 1.1,
      scaleRatio: 2,
      googleFonts: [
        { name: 'IBM Plex Sans', styles: ['400', '600'] },
        { name: 'IBM Plex Serif', styles: ['400'] },
      ],
      headerFontFamily: ['IBM Plex Sans', 'Helvetica'],
      bodyFontFamily: ['IBM Plex Serif', 'sans-serif'],
      headerWeight: 'bold',
      bodyWeight: 'normal',
      boldWeight: 'bold',
      includeNormalize: true,
      blockMarginBottom: 1,
      rhythmUnit: 'px',
    },
  },
};
